FROM php:7.3-fpm-alpine
RUN apk update && apk add postgresql-dev
RUN docker-php-ext-install pdo pdo_pgsql pgsql
COPY --from=composer /usr/bin/composer /usr/bin/composer
WORKDIR /var/www
CMD php-fpm
EXPOSE 9000
